import type { Tool } from './types';
export const MOCK_TOOLS: Tool[] = [
  {
    id: '1',
    title: 'Headline Generator',
    description: 'Generate hundreds of headline ideas for your blog posts, ads, and social media content in seconds.',
    category: 'Copywriting',
    cost: 2,
    tags: ['AI', 'Marketing', 'Content'],
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-2858200f7426?q=80&w=800&auto=format&fit=crop',
    content: 'This is an interactive headline generation tool. Provide a topic and tone to generate headlines.',
    rating: 0,
    reviewCount: 0,
  },
  {
    id: '2',
    title: 'A/B Test Calculator',
    description: 'Determine the statistical significance of your A/B tests with this easy-to-use calculator.',
    category: 'Analytics',
    cost: 1,
    tags: ['CRO', 'Testing', 'Data'],
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
    content: 'This is an interactive A/B test significance calculator. Enter your variant data to see the results.',
    rating: 0,
    reviewCount: 0,
  },
  {
    id: '3',
    title: 'Social Media Calendar Template',
    description: 'Plan and organize your social media content with this customizable calendar template for Notion.',
    category: 'Social Media',
    cost: 3,
    tags: ['Planning', 'Templates', 'Organization'],
    imageUrl: 'https://images.unsplash.com/photo-1611162617213-6d22e525b389?q=80&w=800&auto=format&fit=crop',
    content: 'This is the locked content for the Social Media Calendar.',
    rating: 0,
    reviewCount: 0,
  },
  {
    id: '4',
    title: 'SEO Keyword Rank Tracker',
    description: 'A simple but powerful tool to track your website\'s keyword rankings on Google over time.',
    category: 'SEO',
    cost: 5,
    tags: ['SEO', 'Tracking', 'Keywords'],
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=800&auto=format&fit=crop',
    content: 'This is the locked content for the SEO Keyword Rank Tracker.',
    rating: 0,
    reviewCount: 0,
  },
  {
    id: '5',
    title: 'Email Subject Line Tester',
    description: 'Improve your open rates by testing your email subject lines against proven best practices.',
    category: 'Email Marketing',
    cost: 2,
    tags: ['Email', 'Copywriting', 'AI'],
    imageUrl: 'https://images.unsplash.com/photo-1557200134-90327ee9f6d5?q=80&w=800&auto=format&fit=crop',
    content: 'This is an interactive tool to analyze and score your email subject lines.',
    rating: 0,
    reviewCount: 0,
  },
  {
    id: '6',
    title: 'Landing Page Swipe File',
    description: 'A curated collection of high-converting landing page designs for inspiration.',
    category: 'Design',
    cost: 3,
    tags: ['Inspiration', 'CRO', 'UI/UX'],
    imageUrl: 'https://images.unsplash.com/photo-1607703703520-bb2a8e35512d?q=80&w=800&auto=format&fit=crop',
    content: 'This is the locked content for the Landing Page Swipe File.',
    rating: 0,
    reviewCount: 0,
  },
];